In [1]:
import numpy as np
import pandas as pd


In [2]:
df_train=pd.read_csv('A:\\train.csv')

In [3]:
df_test=pd.read_csv('A:\\test.csv')

In [4]:
df_train.drop('ID',inplace=True,axis=1)


In [5]:
df_train.columns


Index(['y', 'X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8', 'X10',
       ...
       'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X382', 'X383', 'X384',
       'X385'],
      dtype='object', length=377)

In [6]:
df_train.head()

y  X0 X1  X2 X3 X4 X5 X6 X8  X10  ...  X375  X376  X377  X378  X379  \
0  130.81   k  v  at  a  d  u  j  o    0  ...     0     0     1     0     0   
1   88.53   k  t  av  e  d  y  l  o    0  ...     1     0     0     0     0   
2   76.26  az  w   n  c  d  x  j  x    0  ...     0     0     0     0     0   
3   80.62  az  t   n  f  d  x  l  e    0  ...     0     0     0     0     0   
4   78.02  az  v   n  f  d  h  d  n    0  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 377 columns]

In [7]:
df_test.drop('ID',inplace=True,axis=1)

In [8]:
df_test.head()

X0 X1  X2 X3 X4 X5 X6 X8  X10  X11  ...  X375  X376  X377  X378  X379  \
0  az  v   n  f  d  t  a  w    0    0  ...     0     0     0     1     0   
1   t  b  ai  a  d  b  g  y    0    0  ...     0     0     1     0     0   
2  az  v  as  f  d  a  j  j    0    0  ...     0     0     0     1     0   
3  az  l   n  f  d  z  l  n    0    0  ...     0     0     0     1     0   
4   w  s  as  c  d  y  i  m    0    0  ...     1     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     0     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 376 columns]

# 1.variance ==0 remove them


In [9]:
zero_var=df_train.var()[df_train.var()==0].index.values

C:\Users\Yuvarajvijay\AppData\Local\Temp\ipykernel_16840\2329610312.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  zero_var=df_train.var()[df_train.var()==0].index.values


In [10]:
df_train.drop(zero_var,inplace=True,axis=1)
df_test.drop(zero_var,inplace=True,axis=1)

# 2. check for null and unique


In [11]:
np.sum(df_train.isnull().sum())

0

In [12]:
np.sum(df_test.isnull().sum())

0

In [13]:
#check for unique

In [14]:
for i in df_train.columns:
    print(df_train[i].unique())

[130.81  88.53  76.26 ...  85.71 108.77  87.48]
['k' 'az' 't' 'al' 'o' 'w' 'j' 'h' 's' 'n' 'ay' 'f' 'x' 'y' 'aj' 'ak' 'am'
 'z' 'q' 'at' 'ap' 'v' 'af' 'a' 'e' 'ai' 'd' 'aq' 'c' 'aa' 'ba' 'as' 'i'
 'r' 'b' 'ax' 'bc' 'u' 'ad' 'au' 'm' 'l' 'aw' 'ao' 'ac' 'g' 'ab']
['v' 't' 'w' 'b' 'r' 'l' 's' 'aa' 'c' 'a' 'e' 'h' 'z' 'j' 'o' 'u' 'p' 'n'
 'i' 'y' 'd' 'f' 'm' 'k' 'g' 'q' 'ab']
['at' 'av' 'n' 'e' 'as' 'aq' 'r' 'ai' 'ak' 'm' 'a' 'k' 'ae' 's' 'f' 'd'
 'ag' 'ay' 'ac' 'ap' 'g' 'i' 'aw' 'y' 'b' 'ao' 'al' 'h' 'x' 'au' 't' 'an'
 'z' 'ah' 'p' 'am' 'j' 'q' 'af' 'l' 'aa' 'c' 'o' 'ar']
['a' 'e' 'c' 'f' 'd' 'b' 'g']
['d' 'b' 'c' 'a']
['u' 'y' 'x' 'h' 'g' 'f' 'j' 'i' 'd' 'c' 'af' 'ag' 'ab' 'ac' 'ad' 'ae'
 'ah' 'l' 'k' 'n' 'm' 'p' 'q' 's' 'r' 'v' 'w' 'o' 'aa']
['j' 'l' 'd' 'h' 'i' 'a' 'g' 'c' 'k' 'e' 'f' 'b']
['o' 'x' 'e' 'n' 's' 'a' 'h' 'p' 'm' 'k' 'd' 'i' 'v' 'j' 'b' 'q' 'w' 'g'
 'y' 'l' 'f' 'u' 'r' 't' 'c']
[0 1]
[0 1]
[1 0]
[0 1]
[0 1]
[0 1]
[0 1]
[1 0]
[0 1]
[0 1]
[1 0]
[0 1]
[0 1]
[0 1]
[0 1]
[0 1]


In [15]:
label_columns=df_train.describe(include='object').columns.values

# 3.Apply label encoder on categorical columns


In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
le=LabelEncoder()

In [18]:
for col in label_columns:
    df_train[col]=le.fit_transform(df_train[col])
    df_test[col]=le.fit_transform(df_test[col])

In [19]:
df_train['X0'].unique()

array([32, 20, 40,  9, 36, 43, 31, 29, 39, 35, 19, 27, 44, 45,  7,  8, 10,
       46, 37, 15, 12, 42,  5,  0, 26,  6, 25, 13, 24,  1, 22, 14, 30, 38,
       21, 18, 23, 41,  4, 16, 34, 33, 17, 11,  3, 28,  2])

# 4. performing dimensionality reduction

In [20]:
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split

In [21]:
pca=PCA(n_components=0.98)

In [22]:
x=df_train.drop('y',axis=1)
y=df_train['y']

In [23]:
y

0       130.81
1        88.53
2        76.26
3        80.62
4        78.02
         ...  
4204    107.39
4205    108.77
4206    109.22
4207     87.48
4208    110.85
Name: y, Length: 4209, dtype: float64

In [24]:
X_train,X_val,y_train,y_val=train_test_split(x,y,test_size=0.2,random_state=42)

In [25]:
pca.fit(x)

PCA(n_components=0.98)

In [26]:
pca.n_components_

14

In [27]:
pca.explained_variance_ratio_

array([0.38334782, 0.21388033, 0.13261866, 0.11826642, 0.09206008,
       0.01590604, 0.0074454 , 0.00433701, 0.00294021, 0.00241796,
       0.00236488, 0.00203229, 0.00167204, 0.00148111])

# 5. predicting using XG boost regressor

In [28]:
pca_xtrain=pca.transform(X_train)
pca_xval=pca.transform(X_val)

In [29]:
from xgboost import XGBRegressor

In [30]:
XG=XGBRegressor()

In [31]:
XG.fit(pca_xtrain,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [32]:
predict=XG.predict(pca_xval)

In [33]:
predict

array([ 90.10554 , 109.085   , 114.9132  ,  76.88776 , 109.66868 ,
       106.69389 ,  92.103004,  99.42944 , 103.91546 , 119.92642 ,
        79.27373 ,  91.66158 , 100.59954 , 100.84466 ,  90.93082 ,
        95.08305 , 109.10988 ,  91.533966,  94.3765  , 114.61338 ,
       107.961205,  90.247406,  86.507996, 101.228836,  92.28475 ,
       111.5217  ,  93.758224,  81.12574 ,  93.17397 ,  93.34288 ,
        93.79184 , 104.37993 ,  95.97737 , 112.678955, 106.68088 ,
       130.94974 , 105.51009 ,  97.5013  ,  95.67043 ,  97.844734,
       114.51808 , 104.40468 , 133.32457 , 112.14565 ,  94.27508 ,
       108.272194,  93.354965,  97.48383 , 109.49894 , 103.00582 ,
        91.99495 , 101.249   ,  97.07281 , 108.53059 ,  93.655205,
        98.69655 ,  97.30478 , 114.0535  ,  96.22599 , 102.07078 ,
       110.46422 ,  75.99392 ,  95.72187 ,  93.77533 ,  77.87379 ,
       100.705986,  89.150276, 105.82625 , 103.00582 ,  94.64265 ,
        94.40081 ,  88.9794  ,  91.36581 , 106.95865 ,  91.940

In [34]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedKFold

In [35]:
cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)

In [36]:
scores = cross_val_score(XG, x, y, scoring='neg_mean_absolute_error', cv=cv, n_jobs=-1)

In [37]:
from numpy import absolute

In [38]:
scores = absolute(scores)
print('Mean MAE: %.3f (%.3f)' % (scores.mean(), scores.std()) )

Mean MAE: 5.953 (0.290)
